### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by cyulin17** [cyulin17/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create a HTML skeleton
- [x] set the background color to the body
- [x] add a car image and set the correct position
