### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by cyulin17** [cyulin17/driving-game#2]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add a location to the data model to hold the car's x and y
- [x] set absolute positioning for the image
- [x] Use the style property of element objects to change the car's top and left box offset styles.
