### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by cyulin17** [cyulin17/driving-game#5]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create a data model that includes which way the car is facing
- [x] add classes for car directions
- [x] listen for a keydown event
